# /etc/nsswitch.conf - GNU Name Service Switch configuration.
# GCP variant: includes oslogin for GCE OS Login user/group resolution.

passwd:         files oslogin
group:          files oslogin
shadow:         files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
