[Content]
Packages=
    systemd-ukify
    systemd-boot-efi

Bootable=enabled
UnifiedKernelImages=unsigned

KernelCommandLine=
    console=ttyS0,115200n8
    lockdown=integrity
    module.sig_enforce=1
